### ISSUE TITLE
Other keys should be disabled when modal is active

### ISSUE THREAD

**Issue by agzam** [agzam/spacehammer#1]
When a modal is active other keys (that have no dedicated action) should be disabled

**Comment by agzam** [comment]
see this https://github.com/Hammerspoon/hammerspoon/issues/1505

**Comment by eccentric-j** [comment]
I think this one has been resolved already right?

**Comment by agzam** [comment]
> I think this one has been resolved already right?

No, it's not really resolved. What it originally meant is to disable **all** the keys except the ones that are available in the modal. The main reasoning was that modals used to "leak" their keys (e.g. if you press `w` in `LEAD m` modal, it would take you to `LEAD w` modal. Your amazing work on the state-machine has fixed that.

But I also wanted to protect the current app from responding to keys that are not present in the modal to avoid confusion on multi-monitor systems.

I think we can close this issue with a "won't fix" flag, it's not too annoying anymore, as it used to be.
